[phases.setup]
nixPkgs = [
    'python310',
    'python310Packages.pip',
    'python310Packages.virtualenv',
    'python310Packages.gunicorn',
    'postgresql',
    'gcc',
    'libffi',
    'zlib',
    'libjpeg',
    'libpqxx',
    'openssl',
    'pkg-config'
]

[phases.install]
cmds = [
    # Crear entorno virtual
    "python -m venv /app/venv",
    # Instalar dependencias directamente con pip del sistema
    "pip install --upgrade pip setuptools wheel",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "python manage.py collectstatic --noinput"
]

[start]
cmd = "gunicorn myproject.wsgi --log-file -"

[build.args]
PYTHONUNBUFFERED = "1"
PYTHONPATH = "/app"

[build.environment]
NIXPKGS_ALLOW_UNFREE = "1"
PYTHONPATH = "/app"