[phases.setup]
nixPkgs = [
    'python310',
    'python310Packages.pip',
    'python310Packages.virtualenv',
    'python310Packages.setuptools',
    'python310Packages.wheel',
    'postgresql',
    'gcc',
    'libffi',
    'zlib',
    'libjpeg',
    'libpqxx',
    'openssl',
    'pkg-config'
]

[phases.install]
cmds = [
    # Crear entorno virtual
    "python -m venv /app/venv",
    # Usar pip del entorno virtual
    "/app/venv/bin/pip install --upgrade pip setuptools wheel",
    # Instalar dependencias básicas primero
    "/app/venv/bin/pip install Django==5.2.3 gunicorn==21.2.0",
    # Instalar el resto de dependencias
    "/app/venv/bin/pip install -r requirements.txt --no-cache-dir",
    # Verificar instalación
    "/app/venv/bin/python -c \"import django; print(f'Django version: {django.__version__}')\""
]

[phases.build]
cmds = [
    "/app/venv/bin/python manage.py collectstatic --noinput --clear"
]

[start]
cmd = "/app/venv/bin/python -m gunicorn myproject.wsgi --log-file - --bind 0.0.0.0:$PORT"

[build.args]
PYTHONUNBUFFERED = "1"
PYTHONPATH = "/app"

[build.environment]
PYTHONUNBUFFERED = "1"
PYTHONPATH = "/app"
NIXPKGS_ALLOW_UNFREE = "1"
PYTHONDONTWRITEBYTECODE = "1"
PYTHONHASHSEED = "random"
PYTHONFAULTHANDLER = "1"