# Generated by Django 5.2.3 on 2025-07-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0002_carritoitem_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="URL de la imagen del producto (opcional si se sube una imagen)",
                null=True,
                verbose_name="URL de la imagen",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="productos/"),
        ),
    ]
